import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          " flex items-center justify-center bg-Cream h-screen w-screen"
        }
      >
        {children}
      </body>
    </html>
  );
}
